# Service
apiVersion: v1
kind: Service
metadata:
  name: orderlabs-backend
  namespace: orderlabs
spec:
  selector:
    app: orderlabs-backend
    version: blue   # 최초엔 blue로 시작
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
